shared:
  time_zone: UTC
  nginx_ipaddresses:
    - 98.85.139.204
development:
  app_domain:
    hostname: thecreatorcentral.localhost
    protocol: http
    port: 3000
  sites_domain:
    hostname: thecreatorcentralsite.localhost
    protocol: http
    port: 3010
  sites:
    base_hostname_segment: ".thecreatorcentralsite.localhost:3010"
    cname_hostname: "sites.thecreatorcentralsite.localhost"
    protocol: http
  services:
    app: "app.thecreatorcentral.localhost:3000"
    sites: "app.thecreatorcentralsite.localhost:3010"
test:
  app_domain:
    hostname: testtcc.localhost
    protocol: http
    port: 3000
  sites_domain:
    hostname: testtccsite.localhost
    protocol: http
    port: 3010
  sites:
    base_hostname_segment: ".testtccsite.example"
    cname_hostname: "sites.testtccsite.example"
    protocol: http
production:
  app_domain:
    hostname: thecreatorcentral.com
    protocol: https
  sites_domain:
    hostname: thecreatorcentral.site
    protocol: https
  sites:
    base_hostname_segment: ".thecreatorcentral.site"
    cname_hostname: "sites.thecreatorcentral.site"
    protocol: https
    app: "app.thecreatorcentral.com"
    sites: "app.thecreatorcentralsite.site"
