list:
  font-size:
    type: :list
    list: ["12px", "14px", "16px", "18px", "20px", "22px", "24px", "26px", "28px", "36px", "48px", "72px"]
  font-weight:
    type: :list
    list: ["normal", "bold"]
  text-style:
    type: :list
    list: ["normal", "italic"]
