#
#
# Subscription Packages/Editions
#
#
packages:
  free:
    name: Free
    enabled: true
    visible: false
    default: true
    no_expiration_date: true
    limits:
      max_sites: 2
      max_pages: 10
      max_image_storage: 50
#      max_articles: 20
#      max_products: 5
      max_users: 1
#      max_tracked_ck_users: 50
#      max_pageviews: 500
      max_metrics_days: 3
      custom_domains: false
      req_cc_branding: true
  basic:
    name: Basic
    enabled: true
    visible: true
    stripe_product:
      test: prod_S6KOcopRMb5EdL
      live: prod_P2KIwkLNNcaNfK
    visible_prices:
      month: basic_month
      year: basic_year
    limits:
      max_sites: 10
      max_pages: 30
      max_image_storage: 1024
#      max_articles: 100
#      max_products: 10
      max_users: 5
#      max_tracked_ck_users: 1000
#      max_pageviews: 5000
      max_metrics_days: 7
      custom_domains: true
      req_cc_branding: false
  plus:
    name: Plus
    enabled: true
    visible: true
    featured: true
    stripe_product:
      test: prod_S6KPDH100z383v
      live: prod_P2KI47O18Iny0b
    visible_prices:
      month: plus_month
      year: plus_year
    limits:
      max_sites: 25
      max_pages: 100
      max_image_storage: 5120
#      max_articles: 500
#      max_products: 20
      max_users: 10
#      max_tracked_ck_users: 5000
#      max_pageviews: 50000
      max_metrics_days: 14
      custom_domains: true
      req_cc_branding: false
  premium:
    name: Premium
    enabled: true
    visible: true
    stripe_product:
      test: prod_S6KQnSKtyjtvlD
      live: prod_P2KJg9kylGIHd7
    visible_prices:
      month: premium_month
      year: premium_year
    limits:
      max_sites: 50
      max_pages: 500
      max_image_storage: 102400
#      max_articles: 1000
#      max_products: 100
      max_users: 20
#      max_tracked_ck_users: 20000
#      max_pageviews: 500000
      max_metrics_days: 30
      custom_domains: true
      req_cc_branding: false
